### ISSUE TITLE
Mirror temple A b-20 locks progress

### ISSUE THREAD

**Issue by Blueye95** [rhelmot/CelesteRandomizer#43] opened 2020-07-31 12:55 UTC
Seed 68, ruleset A, hash 618204636. The intended pathway is through a shute where a strawberry would be in the main game. However this is blocked with a door not visible in debug map, effectively softlocking the player.
![image](https://user-images.githubusercontent.com/69042804/89036880-cc2a2000-d33d-11ea-8512-db444e8e44ee.png)
![image](https://user-images.githubusercontent.com/69042804/89036897-d4825b00-d33d-11ea-8a06-a9a5c60bb2ba.png)

**Comment by rhelmot** [comment] 2020-07-31 23:58
I believe the problem is not that the barrier is blocking you, but that the logic thinks the jumpthru platform on the bottom-left is passable. It'll be fixed in the next patch.

**Closed by rhelmot** 2020-07-31 23:58 UTC
